// <auto-generated />
using System;
using CDR.DataRecipient.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CDR.DataRecipient.Repository.SQL.Migrations
{
    [DbContext(typeof(RecipientDatabaseContext))]
    partial class RecipientDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CDR.DataRecipient.Repository.SQL.Entities.CdrArrangement", b =>
                {
                    b.Property<Guid>("CdrArrangementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JsonDocument")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CdrArrangementId");

                    b.ToTable("CdrArrangement");
                });

            modelBuilder.Entity("CDR.DataRecipient.Repository.SQL.Entities.DataHolderBrand", b =>
                {
                    b.Property<Guid>("DataHolderBrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JsonDocument")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DataHolderBrandId");

                    b.ToTable("DataHolderBrand");
                });

            modelBuilder.Entity("CDR.DataRecipient.Repository.SQL.Entities.Registration", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JsonDocument")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Registration");
                });
#pragma warning restore 612, 618
        }
    }
}
